# Generated by Django 6.0.3 on 2026-03-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='personnel_image',
            field=models.ImageField(blank=True, null=True, upload_to='personnel_images/'),
        ),
    ]
