# Generated by Django 6.0.3 on 2026-03-09 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_add_ammo_return_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='personnel',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['Active', 'Inactive'])), name='personnel_status_valid'),
        ),
    ]
