# Generated by Django 6.0.3 on 2026-04-28 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_personnelsquadron'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='tel',
            field=models.CharField(help_text='Contact telephone number — exactly 11 digits (e.g. 09XXXXXXXXX).', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{11}$', 'Enter exactly 11 digits (e.g. 09XXXXXXXXX).')]),
        ),
    ]
