# Generated by Django 6.0.3 on 2026-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0007_alter_personnel_tel'),
        ('personnel', '0007_perf_add_status_indexes'),
    ]

    operations = [
    ]
