# Generated by Django 6.0.3 on 2026-05-11 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0008_merge_20260428_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='tel',
            field=models.CharField(help_text='Contact telephone number — 10 digits starting with 9 (e.g. 9XXXXXXXXX) or 11 digits starting with 0 (e.g. 09XXXXXXXXX).', max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator('^(9\\d{9}|0\\d{10})$', 'Enter 10 digits starting with 9 (e.g. 9XXXXXXXXX) or 11 digits starting with 0 (e.g. 09XXXXXXXXX).')]),
        ),
    ]
