# Generated by Django 5.1.1 on 2026-03-07 13:53

import armguard.apps.inventory.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField(help_text='Calendar date this snapshot was taken.')),
                ('item_type', models.CharField(choices=[('Small Arms', 'Small Arms'), ('Ammunition', 'Ammunition'), ('Magazines', 'Magazines'), ('Accessories', 'Accessories')], max_length=50)),
                ('weapon_type', models.CharField(blank=True, choices=[('Pistol', 'Pistol'), ('Rifle', 'Rifle')], max_length=10, null=True)),
                ('category', models.CharField(max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0)),
                ('issued_count', models.PositiveIntegerField(default=0)),
                ('available_count', models.PositiveIntegerField(default=0)),
                ('par_count', models.PositiveIntegerField(default=0)),
                ('tr_count', models.PositiveIntegerField(default=0)),
                ('taken_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Exact timestamp when this snapshot row was saved.')),
            ],
            options={
                'verbose_name': 'Analytics Snapshot',
                'verbose_name_plural': 'Analytics Snapshots',
                'ordering': ['-snapshot_date', 'item_type', 'weapon_type', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory_Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Small Arms', 'Small Arms'), ('Ammunition', 'Ammunition'), ('Magazines', 'Magazines'), ('Accessories', 'Accessories')], help_text='Broad item category.', max_length=50)),
                ('weapon_type', models.CharField(blank=True, choices=[('Pistol', 'Pistol'), ('Rifle', 'Rifle')], help_text='Pistol or Rifle — used for magazines and ammunition pools.', max_length=10, null=True)),
                ('category', models.CharField(help_text='Sub-type: weapon model, ammo designation, magazine type, or accessory type.', max_length=100)),
                ('total_count', models.PositiveIntegerField(default=0, help_text='Total number of items registered.', validators=[django.core.validators.MinValueValidator(0)])),
                ('issued_count', models.PositiveIntegerField(default=0, help_text='Number currently issued to personnel.', validators=[django.core.validators.MinValueValidator(0)])),
                ('available_count', models.PositiveIntegerField(default=0, help_text='Number currently available. Should equal total_count - issued_count.', validators=[django.core.validators.MinValueValidator(0)])),
                ('par_count', models.PositiveIntegerField(default=0, help_text='Number of withdrawal transactions issued under PAR (Property Acknowledgement Receipt).', validators=[django.core.validators.MinValueValidator(0)])),
                ('tr_count', models.PositiveIntegerField(default=0, help_text='Number of withdrawal transactions issued under TR (Temporary Receipt).', validators=[django.core.validators.MinValueValidator(0)])),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of last analytics snapshot update.')),
            ],
            options={
                'verbose_name': 'Inventory Analytics',
                'verbose_name_plural': 'Inventory Analytics',
                'ordering': ['item_type', 'weapon_type', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Ammunition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Cal.45 Ball 433 Ctg', 'Cal.45 Ball 433 Ctg'), ('M882 9x19mm Ball 435 Ctg', 'M882 9x19mm Ball 435 Ctg'), ('M193 5.56mm Ball 428 Ctg', 'M193 5.56mm Ball 428 Ctg'), ('M855 5.56mm Ball 429 Ctg', 'M855 5.56mm Ball 429 Ctg'), ('M80 7.62x51mm Ball 431 Ctg', 'M80 7.62x51mm Ball 431 Ctg')], max_length=30)),
                ('lot_number', models.CharField(help_text='Lot/batch number for this ammunition consignment.', max_length=50, unique=True)),
                ('quantity', models.PositiveIntegerField(help_text='Total number of rounds currently in stock.', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category classification for this ammunition lot.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ammunition', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Pistol Magazine Pouch', 'Pistol Magazine Pouch'), ('Pistol Holster', 'Pistol Holster'), ('Rifle Sling', 'Rifle Sling'), ('Bandoleer', 'Bandoleer')], max_length=50)),
                ('quantity', models.PositiveIntegerField(help_text='Total number of units currently in stock.')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category classification for this accessory pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessories', to='inventory.category')),
            ],
            options={
                'verbose_name': 'Accessory',
                'verbose_name_plural': 'Accessories',
            },
        ),
        migrations.CreateModel(
            name='Magazine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon_type', models.CharField(choices=[('Pistol', 'Pistol'), ('Rifle', 'Rifle')], default='Rifle', help_text='Whether this magazine pool is for pistols or rifles. Auto-set by save() from type.', max_length=10)),
                ('type', models.CharField(choices=[('Pistol Standard', 'Pistol Standard'), ('Short', 'Short'), ('Long', 'Long')], max_length=30)),
                ('capacity', models.CharField(blank=True, max_length=10)),
                ('quantity', models.PositiveIntegerField(help_text='Total number of magazine units currently in stock.', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category classification for this magazine pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='magazines', to='inventory.category')),
            ],
        ),
        migrations.CreateModel(
            name='Pistol',
            fields=[
                ('item_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('item_number', models.CharField(blank=True, help_text='Sequential number within the same pistol model. Auto-assigned.', max_length=4)),
                ('model', models.CharField(choices=[('Glock 17 9mm', 'Glock 17 9mm'), ('M1911 Cal.45', 'M1911 Cal.45'), ('Armscor Hi Cap Cal.45', 'Armscor Hi Cap Cal.45'), ('RIA Hi Cap Cal.45', 'RIA Hi Cap Cal.45'), ('M1911 Customized Cal.45', 'M1911 Customized Cal.45')], max_length=30)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('serial_image', models.ImageField(blank=True, null=True, upload_to=armguard.apps.inventory.models.Pistol.serial_image_upload_to)),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_code_images_pistol')),
                ('item_tag', models.ImageField(blank=True, null=True, upload_to='item_id_tags')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('item_condition', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable'), ('Lost', 'Lost'), ('Tampered', 'Tampered')], default='Serviceable', max_length=20)),
                ('item_status', models.CharField(choices=[('Issued', 'Issued'), ('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('For Turn In', 'For Turn In'), ('Turned In', 'Turned In'), ('Decommissioned', 'Decommissioned')], default='Available', max_length=20)),
                ('item_assigned_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_assigned_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('item_issued_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_issued_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category classification for this pistol (e.g., Small Arms).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pistols', to='inventory.category')),
                ('item_assigned_to', models.ForeignKey(blank=True, help_text='Personnel this pistol is pre-assigned to. Set via set_assigned() only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pistols_assigned', to='personnel.personnel')),
                ('item_issued_to', models.ForeignKey(blank=True, help_text='Personnel this pistol is currently issued to. Set via Transactions only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pistols_issued', to='personnel.personnel')),
            ],
            options={
                'unique_together': {('item_number', 'model')},
            },
        ),
        migrations.CreateModel(
            name='Rifle',
            fields=[
                ('item_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('item_number', models.CharField(blank=True, help_text='Sequential number within the same rifle model. Auto-assigned.', max_length=4)),
                ('model', models.CharField(choices=[('M4 Carbine DSAR-15 5.56mm', 'M4 Carbine DSAR-15 5.56mm'), ('M4 14.5" DGIS EMTAN 5.56mm', 'M4 14.5" DGIS EMTAN 5.56mm'), ('M16A1 Rifle 5.56mm', 'M16A1 Rifle 5.56mm'), ('M14 Rifle 7.62mm', 'M14 Rifle 7.62mm'), ('M653 Carbine 5.56mm', 'M653 Carbine 5.56mm')], max_length=30)),
                ('factory_qr', models.CharField(blank=True, help_text='Factory QR code (required for M4 Carbine DSAR-15 5.56mm only).', max_length=100, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('serial_image', models.ImageField(blank=True, null=True, upload_to=armguard.apps.inventory.models.Rifle.serial_image_upload_to)),
                ('qr_code', models.CharField(editable=False, max_length=100, unique=True)),
                ('qr_code_image', models.ImageField(blank=True, null=True, upload_to='qr_code_images_rifle')),
                ('item_tag', models.ImageField(blank=True, null=True, upload_to='item_id_tags')),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('item_condition', models.CharField(choices=[('Serviceable', 'Serviceable'), ('Unserviceable', 'Unserviceable'), ('Lost', 'Lost'), ('Tampered', 'Tampered')], default='Serviceable', max_length=20)),
                ('item_status', models.CharField(choices=[('Issued', 'Issued'), ('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('For Turn In', 'For Turn In'), ('Turned In', 'Turned In'), ('Decommissioned', 'Decommissioned')], default='Available', max_length=20)),
                ('item_assigned_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_assigned_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('item_issued_timestamp', models.DateTimeField(blank=True, default=None, null=True)),
                ('item_issued_by', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('category', models.ForeignKey(blank=True, help_text='Optional category classification for this rifle (e.g., Small Arms).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifles', to='inventory.category')),
                ('item_assigned_to', models.ForeignKey(blank=True, help_text='Personnel this rifle is pre-assigned to. Set via set_assigned() only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifles_assigned', to='personnel.personnel')),
                ('item_issued_to', models.ForeignKey(blank=True, help_text='Personnel this rifle is currently issued to. Set via Transactions only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rifles_issued', to='personnel.personnel')),
            ],
            options={
                'unique_together': {('item_number', 'model')},
            },
        ),
    ]
