# Generated by Django 6.0.3 on 2026-03-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('personnel', '0003_g8_db_constraints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ammunition',
            options={'verbose_name': 'Ammunition', 'verbose_name_plural': 'Ammunition'},
        ),
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Magazine', 'verbose_name_plural': 'Magazines'},
        ),
        migrations.AddConstraint(
            model_name='accessory',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='accessory_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='ammunition',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='ammunition_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='magazine',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='magazine_quantity_nonneg'),
        ),
        migrations.AddConstraint(
            model_name='pistol',
            constraint=models.CheckConstraint(condition=models.Q(('item_status__in', ['Issued', 'Available', 'Under Maintenance', 'For Turn In', 'Turned In', 'Decommissioned'])), name='pistol_item_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='pistol',
            constraint=models.CheckConstraint(condition=models.Q(('item_condition__in', ['Serviceable', 'Unserviceable', 'Lost', 'Tampered'])), name='pistol_item_condition_valid'),
        ),
        migrations.AddConstraint(
            model_name='rifle',
            constraint=models.CheckConstraint(condition=models.Q(('item_status__in', ['Issued', 'Available', 'Under Maintenance', 'For Turn In', 'Turned In', 'Decommissioned'])), name='rifle_item_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='rifle',
            constraint=models.CheckConstraint(condition=models.Q(('item_condition__in', ['Serviceable', 'Unserviceable', 'Lost', 'Tampered'])), name='rifle_item_condition_valid'),
        ),
    ]
