# Generated by Django 6.0.3 on 2026-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_firearm_discrepancy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firearmdiscrepancy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
