# Generated by Django 6.0.3 on 2026-04-01 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_firearmdiscrepancy_extra_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='pistol',
            name='property_number',
            field=models.CharField(blank=True, help_text='Government / property custodian number assigned to this pistol. Leave blank if not yet assigned.', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='rifle',
            name='property_number',
            field=models.CharField(blank=True, help_text='Government / property custodian number assigned to this rifle. Leave blank if not yet assigned.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pistol',
            name='item_number',
            field=models.CharField(help_text='Required. Unique number within the same pistol model (e.g. 0001). Must be entered manually.', max_length=4),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='item_number',
            field=models.CharField(help_text='Required. Unique number within the same rifle model (e.g. 0001). Must be entered manually.', max_length=4),
        ),
    ]
