# Generated by Django 6.0.3 on 2026-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_add_property_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifle',
            name='model',
            field=models.CharField(choices=[('M4 Carbine DSAR-15 5.56mm', 'M4 Carbine DSAR-15 5.56mm'), ('M4 14.5" DGIS EMTAN 5.56mm', 'M4 14.5" DGIS EMTAN 5.56mm'), ('M16A1 Rifle 5.56mm', 'M16 Rifle 5.56mm'), ('M14 Rifle 7.62mm', 'M14 Rifle 7.62mm'), ('M653 Carbine 5.56mm', 'M653 Carbine 5.56mm')], max_length=30),
        ),
    ]
