# Generated by Django 6.0.3 on 2026-04-28 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_alter_rifle_model'),
        ('inventory', '0013_perf_add_status_indexes'),
    ]

    operations = [
    ]
