# Generated by Django 6.0.3 on 2026-05-08 15:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_emtan_capacity_fix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ammunition',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Total number of rounds currently in stock.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Total number of magazine units currently in stock.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rifle',
            name='model',
            field=models.CharField(choices=[('M4 Carbine DSAR-15 5.56mm', 'M4 Carbine DSAR-15 5.56mm'), ('M4 14.5" DGIS EMTAN 5.56mm', 'M4 14.5" DGIS EMTAN 5.56mm'), ('M16A1 Rifle 5.56mm', 'M16A1 Rifle 5.56mm'), ('M14 Rifle 7.62mm', 'M14 Rifle 7.62mm'), ('M653 Carbine 5.56mm', 'M653 Carbine 5.56mm')], max_length=30),
        ),
    ]
