# Generated by Django 5.1.1 on 2026-03-07 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('role', models.CharField(choices=[('System Administrator', 'System Administrator'), ('Administrator', 'Administrator'), ('Armorer', 'Armorer')], default='Armorer', help_text='System role for this user. System Administrator = full admin access; Administrator = full access; Armorer = transactions and logs.', max_length=30)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
