# Generated by Django 6.0.3 on 2026-03-09 03:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auditlog_and_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='integrity_hash',
            field=models.CharField(blank=True, help_text='SHA-256 of (timestamp + username + action + message) — set on save.', max_length=64),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user_agent',
            field=models.CharField(blank=True, help_text='HTTP User-Agent header from the request.', max_length=512),
        ),
        migrations.CreateModel(
            name='DeletedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('object_pk', models.CharField(max_length=100)),
                ('data', models.TextField(help_text='JSON snapshot of the deleted object.')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deleted Record',
                'verbose_name_plural': 'Deleted Records',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
