# Generated by Django 6.0.3 on 2026-03-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perm_can_add',
            field=models.BooleanField(default=True, help_text='Administrator: allowed to create new records. Has no effect on System Administrator or Armorer.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_can_edit',
            field=models.BooleanField(default=True, help_text='Administrator: allowed to edit existing records. Has no effect on System Administrator or Armorer.'),
        ),
    ]
