# Generated by Django 6.0.3 on 2026-03-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_admin_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='perm_can_add',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='perm_can_edit',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_inventory_add',
            field=models.BooleanField(default=False, help_text='May create new inventory records.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_inventory_delete',
            field=models.BooleanField(default=False, help_text='May delete inventory records.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_inventory_edit',
            field=models.BooleanField(default=False, help_text='May edit existing inventory records.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_inventory_view',
            field=models.BooleanField(default=False, help_text='May view inventory lists (pistols, rifles, ammo, magazines, accessories).'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_personnel_add',
            field=models.BooleanField(default=False, help_text='May create new personnel records.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_personnel_delete',
            field=models.BooleanField(default=False, help_text='May delete personnel records.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_personnel_edit',
            field=models.BooleanField(default=False, help_text='May edit personnel records and assign weapons.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_personnel_view',
            field=models.BooleanField(default=False, help_text='May view personnel list and detail pages.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_reports',
            field=models.BooleanField(default=False, help_text='May access print pages, generate/regenerate ID cards and item tags, and download reports.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_transaction_create',
            field=models.BooleanField(default=False, help_text='May create new withdrawal/return transactions.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_transaction_view',
            field=models.BooleanField(default=False, help_text='May view transaction list and detail pages.'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='perm_users_manage',
            field=models.BooleanField(default=False, help_text='May view, create, edit, and delete user accounts.'),
        ),
    ]
