# Generated by Django 6.0.3 on 2026-03-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_per_module_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perm_print',
            field=models.BooleanField(default=False, help_text='May access the Print module: generate/print ID cards, item tags, and PDF transaction forms.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='perm_reports',
            field=models.BooleanField(default=False, help_text='May view and download analytical reports.'),
        ),
    ]
