# Generated by Django 6.0.3 on 2026-03-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_add_perm_print'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('System Administrator', 'System Administrator'), ('Administrator — View Only', 'Administrator — View Only'), ('Administrator — Edit & Add', 'Administrator — Edit & Add'), ('Armorer', 'Armorer')], default='Armorer', help_text='System role for this user. System Administrator = full admin access; Administrator = full access; Armorer = transactions and logs.', max_length=30),
        ),
    ]
