# Generated by Django 6.0.3 on 2026-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_role_choices_admin_subtypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commander_name', models.CharField(blank=True, default='', max_length=100)),
                ('commander_rank', models.CharField(blank=True, default='', max_length=50)),
                ('commander_branch', models.CharField(blank=True, default='PAF', max_length=20)),
                ('commander_designation', models.CharField(blank=True, default='Squadron Commander', max_length=100)),
                ('armorer_branch', models.CharField(blank=True, default='PAF', max_length=20)),
                ('pistol_magazine_max_qty', models.PositiveSmallIntegerField(default=4)),
                ('rifle_magazine_max_qty', models.PositiveSmallIntegerField(blank=True, help_text='Leave blank for no limit.', null=True)),
                ('unit_name', models.CharField(blank=True, default='950th CEWW', max_length=150)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
