# Generated by Django 6.0.3 on 2026-03-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_system_settings_singleton'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='mfa_required',
            field=models.BooleanField(default=True, help_text='Require two-factor authentication (2FA/TOTP) for all users.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_history_count',
            field=models.PositiveSmallIntegerField(default=5, help_text='Number of previous passwords a user may not reuse (0 = no restriction).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='password_min_length',
            field=models.PositiveSmallIntegerField(default=8, help_text='Minimum number of characters required for user passwords (1–128).'),
        ),
    ]
