# Generated by Django 6.0.3 on 2026-03-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_security_fields_and_mfa_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='require_2fa',
            field=models.BooleanField(default=True, help_text='Require TOTP two-factor authentication for this specific user. Only takes effect when the site-wide 2FA setting is also ON. Uncheck to exempt this account from 2FA enforcement.'),
        ),
    ]
