# Generated by Django 6.0.3 on 2026-04-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_systemsettings_purpose_field_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='timeout_admin_edit_add',
            field=models.PositiveIntegerField(default=1800, help_text='Idle timeout in seconds for Administrator — Edit & Add accounts (0 = never).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timeout_admin_view_only',
            field=models.PositiveIntegerField(default=1800, help_text='Idle timeout in seconds for Administrator — View Only accounts (0 = never).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timeout_armorer',
            field=models.PositiveIntegerField(default=3600, help_text='Idle timeout in seconds for Armorer accounts (0 = never).'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timeout_superuser',
            field=models.PositiveIntegerField(default=0, help_text='Idle timeout in seconds for Superuser accounts (0 = never). Default: disabled.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='timeout_system_admin',
            field=models.PositiveIntegerField(default=1800, help_text='Idle timeout in seconds for System Administrator accounts (0 = never).'),
        ),
    ]
