# Generated by Django 6.0.3 on 2026-04-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_systemsettings_rifle_mag_short_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='duty_security_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per Duty Security withdrawal.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='duty_sentinel_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per Duty Sentinel withdrawal.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='duty_vigil_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per Duty Vigil withdrawal.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='honor_guard_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per Honor Guard withdrawal.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='orex_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per OREX withdrawal.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='others_rifle_short_mag_qty',
            field=models.PositiveSmallIntegerField(default=7, help_text='Rifle Short (20-rd) magazines auto-issued per Others withdrawal.'),
        ),
    ]
