# Generated by Django 6.0.3 on 2026-04-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_systemsettings_duty_security_rifle_short_mag_qty_and_more'),
        ('users', '0024_perf_add_status_indexes'),
    ]

    operations = [
    ]
