# Generated by Django 6.0.3 on 2026-03-23 15:10

import armguard.apps.camera.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_camera_upload_log'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CameraDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(default=armguard.apps.camera.models._generate_device_token, editable=False, help_text='Permanent 256-bit identity token. Shared once via QR. Regenerating resets pairing.', max_length=64, unique=True)),
                ('device_name', models.CharField(blank=True, help_text="Optional label (e.g. 'Sgt. Santos — Samsung A54').", max_length=100)),
                ('device_fingerprint', models.CharField(blank=True, editable=False, help_text='HTTP User-Agent captured at first activation.', max_length=512)),
                ('is_active', models.BooleanField(default=False, help_text='QR has been scanned and device is not revoked.')),
                ('paired_at', models.DateTimeField(auto_now_add=True, help_text='When this record was created by an admin.')),
                ('activated_at', models.DateTimeField(blank=True, help_text='When the armorer first scanned the QR.', null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, help_text='Last successful upload timestamp.', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0, help_text='Consecutive failed API-key attempts since last success.')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Device locked until this time after 5 consecutive failures (30-minute lockout).', null=True)),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Administrator who revoked this device.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_camera_devices', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(help_text='One registered device per armorer. Enforced at database level.', on_delete=django.db.models.deletion.CASCADE, related_name='camera_device', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Camera Device',
                'verbose_name_plural': 'Camera Devices',
                'ordering': ['user__username'],
            },
        ),
        migrations.AddField(
            model_name='camerauploadlog',
            name='device',
            field=models.ForeignKey(blank=True, help_text='The paired device that performed this upload.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_logs', to='camera.cameradevice'),
        ),
    ]
