# Generated by Django 6.0.3 on 2026-03-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_cameradevice_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameradevice',
            name='current_pin',
            field=models.CharField(blank=True, help_text='Current 6-digit PIN (rotates every 30 s). Empty until first generated.', max_length=6),
        ),
    ]
