# Generated by Django 6.0.3 on 2026-03-09 01:11

import armguard.apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('personnel', '0002_add_ammo_return_indexes'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='par_document',
            field=models.FileField(blank=True, help_text='Required for PAR issuance: upload signed PAR document (PDF). File will be renamed to PAR_rank_lastname_transactionID.pdf automatically.', null=True, upload_to='PAR_PDF/', validators=[armguard.apps.transactions.models._validate_pdf_extension]),
        ),
        migrations.AddIndex(
            model_name='transactionlogs',
            index=models.Index(fields=['personnel_id', 'withdraw_pistol_ammunition', 'return_pistol_ammunition'], name='tlog_pammo_return_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionlogs',
            index=models.Index(fields=['personnel_id', 'withdraw_rifle_ammunition', 'return_rifle_ammunition'], name='tlog_rammo_return_idx'),
        ),
    ]
