# Generated by Django 6.0.3 on 2026-03-09 03:46

import armguard.apps.transactions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_add_ammo_return_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='par_document',
            field=models.FileField(blank=True, help_text='Required for PAR issuance: upload signed PAR document (PDF). File will be renamed to PAR_rank_lastname_transactionID.pdf automatically.', null=True, upload_to=armguard.apps.transactions.models._sanitize_par_upload, validators=[armguard.apps.transactions.models._validate_pdf_extension]),
        ),
    ]
