# Generated by Django 6.0.3 on 2026-03-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_sanitize_par_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='return_by',
            field=models.DateTimeField(blank=True, help_text='Deadline for returning the issued firearm(s). Applicable to TR (Temporary Receipt) withdrawals.', null=True),
        ),
    ]
