# Generated by Django 6.0.3 on 2026-05-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Add the txn_timestamp_idx index.

    SeparateDatabaseAndState is used so that:
    - Django state records AddIndex (prevents makemigrations auto-generating 0010+)
    - Database uses CREATE INDEX IF NOT EXISTS (idempotent; never crashes if index exists)
    """

    dependencies = [
        ('inventory', '0017_alter_ammunition_quantity_alter_magazine_quantity_and_more'),
        ('personnel', '0008_merge_20260428_2327'),
        ('transactions', '0005_backfill_tr_return_by'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddIndex(
                    model_name='transaction',
                    index=models.Index(fields=['timestamp'], name='txn_timestamp_idx'),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql='CREATE INDEX IF NOT EXISTS txn_timestamp_idx ON transactions_transaction (timestamp);',
                    reverse_sql='DROP INDEX IF EXISTS txn_timestamp_idx;',
                ),
            ],
        ),
    ]

