# Generated by Django 6.0.3 on 2026-05-09 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_transaction_txn_timestamp_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='purpose',
            field=models.CharField(default='Duty Sentinel', help_text="Purpose for this transaction. Custom values are allowed when 'Others' is selected.", max_length=100),
        ),
    ]
