# Generated by Django 6.0.3 on 2026-05-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_change_purpose_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionPurpose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Purpose label shown in the transaction form dropdown.', max_length=100, unique=True)),
                ('hotkey', models.CharField(blank=True, default='', help_text='Keyboard shortcut shown on the transaction form (e.g. "1", "F2").', max_length=20)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order in dropdowns — lower numbers appear first.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive purposes are hidden from the transaction form.')),
                ('is_others_type', models.BooleanField(default=False, help_text='If True a free-text input appears so the operator can type a custom purpose.')),
                ('show_pistol', models.BooleanField(default=True)),
                ('show_rifle', models.BooleanField(default=True)),
                ('auto_consumables', models.BooleanField(default=False, help_text='Auto-assign magazines & ammunition for withdrawals of this purpose.')),
                ('auto_accessories', models.BooleanField(default=False, help_text='Auto-assign accessories for withdrawals of this purpose.')),
                ('auto_print_tr', models.BooleanField(default=False, help_text='Auto-open the TR print page after saving a TR Withdrawal of this purpose.')),
                ('holster_qty', models.PositiveSmallIntegerField(default=1)),
                ('mag_pouch_qty', models.PositiveSmallIntegerField(default=1)),
                ('pistol_mag_qty', models.PositiveSmallIntegerField(default=0)),
                ('pistol_ammo_qty', models.PositiveSmallIntegerField(default=0)),
                ('rifle_sling_qty', models.PositiveSmallIntegerField(default=1)),
                ('rifle_short_mag_qty', models.PositiveSmallIntegerField(default=0)),
                ('rifle_long_mag_qty', models.PositiveSmallIntegerField(default=0)),
                ('rifle_ammo_qty', models.PositiveSmallIntegerField(default=0)),
                ('bandoleer_qty', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Transaction Purpose',
                'verbose_name_plural': 'Transaction Purposes',
                'ordering': ['order', 'name'],
            },
        ),
    ]
