# Generated by Django 6.0.3 on 2026-05-11 08:24

from django.db import migrations

# Default seed data for TransactionPurpose.
# Values match the SystemSettings defaults that were previously hardcoded.
_DEFAULT_PURPOSES = [
    {
        'name': 'Duty Sentinel', 'hotkey': '1', 'order': 10,
        'is_active': True,  'is_others_type': False,
        'show_pistol': True,  'show_rifle': False,
        'auto_consumables': True,  'auto_accessories': True, 'auto_print_tr': False,
        'holster_qty': 1, 'mag_pouch_qty': 1, 'pistol_mag_qty': 4,
        'pistol_ammo_qty': 42, 'rifle_sling_qty': 0, 'rifle_short_mag_qty': 0,
        'rifle_long_mag_qty': 0, 'rifle_ammo_qty': 0, 'bandoleer_qty': 0,
    },
    {
        'name': 'Duty Vigil', 'hotkey': '2', 'order': 20,
        'is_active': True,  'is_others_type': False,
        'show_pistol': False, 'show_rifle': True,
        'auto_consumables': False, 'auto_accessories': False, 'auto_print_tr': False,
        'holster_qty': 0, 'mag_pouch_qty': 1, 'pistol_mag_qty': 0,
        'pistol_ammo_qty': 0, 'rifle_sling_qty': 1, 'rifle_short_mag_qty': 7,
        'rifle_long_mag_qty': 7, 'rifle_ammo_qty': 210, 'bandoleer_qty': 0,
    },
    {
        'name': 'Duty Security', 'hotkey': '3', 'order': 30,
        'is_active': True,  'is_others_type': False,
        'show_pistol': True,  'show_rifle': True,
        'auto_consumables': True,  'auto_accessories': False, 'auto_print_tr': False,
        'holster_qty': 1, 'mag_pouch_qty': 1, 'pistol_mag_qty': 4,
        'pistol_ammo_qty': 42, 'rifle_sling_qty': 1, 'rifle_short_mag_qty': 7,
        'rifle_long_mag_qty': 7, 'rifle_ammo_qty': 210, 'bandoleer_qty': 0,
    },
    {
        'name': 'Honor Guard', 'hotkey': '4', 'order': 40,
        'is_active': True,  'is_others_type': False,
        'show_pistol': False, 'show_rifle': True,
        'auto_consumables': False, 'auto_accessories': False, 'auto_print_tr': False,
        'holster_qty': 1, 'mag_pouch_qty': 1, 'pistol_mag_qty': 2,
        'pistol_ammo_qty': 21, 'rifle_sling_qty': 1, 'rifle_short_mag_qty': 7,
        'rifle_long_mag_qty': 7, 'rifle_ammo_qty': 210, 'bandoleer_qty': 0,
    },
    {
        'name': 'Others', 'hotkey': '5', 'order': 50,
        'is_active': True,  'is_others_type': True,
        'show_pistol': True,  'show_rifle': True,
        'auto_consumables': False, 'auto_accessories': False, 'auto_print_tr': False,
        'holster_qty': 1, 'mag_pouch_qty': 1, 'pistol_mag_qty': 4,
        'pistol_ammo_qty': 42, 'rifle_sling_qty': 1, 'rifle_short_mag_qty': 7,
        'rifle_long_mag_qty': 7, 'rifle_ammo_qty': 210, 'bandoleer_qty': 0,
    },
    {
        'name': 'OREX', 'hotkey': '6', 'order': 60,
        'is_active': True,  'is_others_type': False,
        'show_pistol': True,  'show_rifle': True,
        'auto_consumables': True,  'auto_accessories': False, 'auto_print_tr': False,
        'holster_qty': 1, 'mag_pouch_qty': 1, 'pistol_mag_qty': 4,
        'pistol_ammo_qty': 42, 'rifle_sling_qty': 1, 'rifle_short_mag_qty': 7,
        'rifle_long_mag_qty': 7, 'rifle_ammo_qty': 210, 'bandoleer_qty': 0,
    },
]


def _seed_purposes(apps, schema_editor):
    TransactionPurpose = apps.get_model('transactions', 'TransactionPurpose')
    for data in _DEFAULT_PURPOSES:
        TransactionPurpose.objects.get_or_create(name=data['name'], defaults=data)


def _unseed_purposes(apps, schema_editor):
    TransactionPurpose = apps.get_model('transactions', 'TransactionPurpose')
    names = [d['name'] for d in _DEFAULT_PURPOSES]
    TransactionPurpose.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_transactionpurpose'),
    ]

    operations = [
        migrations.RunPython(_seed_purposes, _unseed_purposes),
    ]
